---
title: "Lecture: Introduction to Rstudio and Images"
linktitle: "1. Introduction to RStudio and Images"
date: "2020-03-31"
class_date: "2020-03-31"
output:
  blogdown::html_page:
    toc: true
menu:
  class:
    parent: Class sessions
    weight: 1
type: docs
weight: 1
# pdf: 
# thumb: 
editor_options: 
  chunk_output_type: console
---

## Slides

### Collaborative Lecture Notes

Click the link below to start editing the class notes. You will need to add to these to participate in the class activity.

https://hackmd.io/@laderast/HkyAfj1vI/edit

### Class Introduction

Open the class introduction slides in a separate window: <a href="https://stats4neuro.netlify.com/slides/01-introduction_slides#1" target="_blank">https://stats4neuro.netlify.com/slides/01-introduction_slides#1</a>

```{r echo=FALSE}
knitr::include_url('https://stats4neuro.netlify.com/slides/01-introduction_slides#1')
```

### Introduction to Images

Open these slides in a separate window: <a href="https://stats4neuro.netlify.com/slides/01-introduction_to_images#1" target="_blank">https://stats4neuro.netlify.com/slides/01-introduction_to_images#1</a>

```{r echo=FALSE}
knitr::include_url('https://stats4neuro.netlify.com/slides/01-introduction_to_images#1')
``````

